include: [".well-known"]
remote_theme: pmarsceill/just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: blue


# Changes
logo: "ocs_logo.png"
title: Commonsense.Run - The Portal Site for Commonsense Reasoning Research
email: yuchen.lin@usc.edu
description: >- # this means to ignore newlines until "baseurl:"
  An online compendium of commonsense knowledge & reasoning, maintained by Bill Yuchen Lin. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://commonsense.run" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OpenCommonSense
github_username:  yuchenlin

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: " "

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/OpenCommonSense/CommonSensePortalSite" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

